- name: ProjetDevops
  hosts: all
  become: yes
  
  tasks:
 
  - name: update
    command: apt-get update
    
  - name: install docker and Python
    apt:
      name: python3, python3-pip, docker.io
      state: present
      
  - name: start docker
    service:
      name: docker
      state: started
      
  - name: install docker python module
    pip:
      name: docker
      
  - name: clone git
    git:
      repo: https://github.com/VuagnatV/ProjetDevops.git
      accept_hostkey: true
      dest: ./repo/
      clone: yes
      update: yes

  #- name: create directory 
   # command: mkdir -p ./mySQLDatabase

 # - name: copy dockerfile 2
  #  command: cp ./repo/mySQLDatabase/Dockerfile ./mySQLDatabase/Dockerfile

# - name: copy dockerfile 3
 #   command: cp ./repo/mySQLDatabase/mysqlsampledatabase.sql ./mySQLDatabase/
       
  - name: build image 2
    docker_image:
      build: 
        path: ./repo/mySQLDatabase
      name: testdata
      source: build
      force_source: true

  - name: run test 2 container
    docker_container:
      name: testdata
      image: testdata
      ports: 8000:3306
      
  - name: copy dockerfile
    command: cp ./repo/Dockerfile ./Dockerfile
       
  - name: build image
    docker_image:
      build: 
        path: ./
      name: test
      source: build
      force_source: true
      
  - name: create volume
    docker_volume:
      name: volume_test
    
  - name: copy html
    command: cp ./repo/HTTPServer/index.php /var/lib/docker/volumes/volume_test/_data/
      
  - name: run test container
    docker_container:
      name: test
      image: test
      volumes:
        #- volume_test:/usr/share/nginx/html
        - volume_test:/var/www/html
      ports: 80:8080
    
  
