- name: ProjetDevops
  hosts: all
  become: yes
  
  tasks:
 
  - name: update
    command: apt-get update
    
  - name: install docker and Python
    apt:
      name: python3, python3-pip, docker.io
      state: present
      
  - name: start docker
    service:
      name: docker
      state: started
      
  - name: install docker python module
    pip:
      name: docker
      
  - name: clone git
    git:
      repo: https://github.com/VuagnatV/ProjetDevops.git
      accept_hostkey: true
      dest: ./repo/
      clone: yes
      update: yes
      
  - name: copy dockerfile
    command: cp ./repo/Dockerfile ./Dockerfile
       
  - name: build image
    docker_image:
      build: 
        path: ./
      name: test
      source: build
      force_source: true
      
  - name: create volume
    docker_volume:
      name: volume_test
    
  - name: copy html
    command: cp ./repo/index.html /var/lib/docker/volumes/volume_test/_data/
      
  - name: run test container
    docker_container:
      name: test
      image: test
      volumes:
        - volume_test:/usr/share/nginx/html
      ports: 8080:80
    
  
