- name: EXO
  hosts: all
  become: yes
  
  tasks:
  - name: check dist
    command: uname -a
    register: result
    
  - name: update
    command: apt-get update
    
  - name: install docker
    apt:
      name: python3, python3-pip, docker.io
      state: present
      
  - name: start docker
    service:
      name: docker
      state: started
      
  - name: install docker python module
    pip:
      name: docker
      
  - name: clone git
    git:
      repo: https://github.com/VuagnatV/ProjetDevops.git
      accept_hostkey: true
      dest: ./repo/
      clone: yes
      update: yes
      
  #- name: git clone
   # command: git clone https://github.com/VuagnatV/Pendu.git
    
  #- name: copy dockerfile
   # copy:
    #  src: ./Dockerfile
     # dest: ./Dockerfile
     
  - name: copy dockerfile
    command: cp ./repo/Dockerfile ./Dockerfile
       
  - name: build image
    docker_image:
      build: 
        path: ./
      name: test
      source: build
      force_source: true
      
  - name: create volume
    docker_volume:
      name: volume_test
      
 # - name: copy html
  #  copy:
   #   src: ./
    #  dest: /var/lib/docker/volumes/volume_test/_data/
    
  - name: copy html
    command: cp ./repo/index.html /var/lib/docker/volumes/volume_test/_data/
      
  - name: run test conteiner
    docker_container:
      name: test
      image: test
      volumes:
        - volume_test:/usr/share/nginx/html
      ports: 8080:80
    
  
    
  #- name: install apache2
   #apt: 
   #   name: apache2
    #  state: present
      
  #- name: copy file
   # copy:
    #  src: /home/vincent/Ansible/dummy.txt
     # dest: /home/vincent-serv/dummy.txt
      #remote_src: yes
   # register: result
    
  - name: display
    debug: 
      msg: "{{result}}"
