- name: ProjetDevops
  hosts: all
  become: yes
  
  tasks:
 
  - name: update
    command: apt-get update
    
  - name: install docker and Python
    apt:
      name: python3, python3-pip, docker.io
      state: present
      
  - name: start docker
    service:
      name: docker
      state: started
      
  - name: install docker python module
    pip:
      name: docker

  - name: create network
    docker_network:
      name: DevopsNet
      
  - name: clone git
    git:
      repo: https://github.com/VuagnatV/ProjetDevops.git
      accept_hostkey: true
      dest: ./repo/
      clone: yes
      update: yes
       
  - name: build mysql image
    docker_image:
      build: 
        path: ./repo/mySQLDatabase
      name: mysqlserv
      source: build
      force_source: true

  - name: run mysqlserv container
    docker_container:
      name: mysqlserv
      image: mysqlserv
      ports: 8000:3306
      networks:
        - name: DevopsNet
          aliases:
            - mysql
       
  - name: build httpserv image
    docker_image:
      build: 
        path: ./repo/HTTPServer/
      name: httpserv
      source: build
      force_source: true
      
  - name: create volume
    docker_volume:
      name: volume_httpserv
    
  - name: copy html
    command: cp ./repo/HTTPServer/index.php /var/lib/docker/volumes/volume_httpserv/_data/
      
  - name: run httpserv container
    docker_container:
      name: httpserv
      image: httpserv
      volumes:
        - volume_httpserv:/var/www/html
      ports: 80:8080
    
  
